- name: create directories for export
  file:
    state: directory
    path: "{{ nfs_server_export_dir }}"
    owner: "{{ nfs_server_export['uid'] }}"
    group: "{{ nfs_server_export['gid'] }}"
    mode: "{{ nfs_server_export['mode'] | default('0750') }}"
  with_items: "{{ nfs_server_export['paths'] }}"
  loop_control:
    loop_var: nfs_server_export_dir
